deployment:
  machine_type: 'n1-standard-8'
  min_replica_count: 1
  max_replica_count: 1
  accelerator_type: 'NVIDIA_TESLA_T4'
  accelerator_count: 1
  traffic_percentage: 100
  service_account: 'vertexai@xyz.iam.gserviceaccount.com'

aiplatform:
  gcp_staging_bucket: 'gs://xyz'
  sa_credentials: '/path/to/service_account_credentials.json'
